blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question
    url: https://github.com/Emerging-Tech-in-Teching-Research/emerging-tech-resources/discussions
    about: Ask questions, share ideas, or get help in Discussions
